### ISSUE TITLE
Unable to run the hexo server

### ISSUE THREAD

**Issue by AlexandreBonneau** [vuejs/vuejs.org#1532]
Following the documentation, on Linux if you clone this repo, then try to start the server it fails:
```
~/dev|» git clone https://github.com/vuejs/vuejs.org.git
Clonage dans 'vuejs.org'...
remote: Counting objects: 22335, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 22335 (delta 1), reused 2 (delta 1), pack-reused 22326
Réception d'objets: 100% (22335/22335), 43.48 MiB | 2.71 MiB/s, fait.
Résolution des deltas: 100% (13674/13674), fait.

~/dev|» cd vuejs.org 

~/dev/vuejs.org|master » lh
total 264K
drwxrwx--x 3 user user 4,0K mars  27 08:42 assets
-rw-rw---- 1 user user 5,3K mars  27 08:42 _config.yml
-rw-rw---- 1 user user 1,1K mars  27 08:42 LICENSE
-rw-rw---- 1 user user  812 mars  27 08:42 package.json
-rw-rw---- 1 user user 132K mars  27 08:42 package-lock.json
-rw-rw---- 1 user user 2,1K mars  27 08:42 pre-deploy.js
-rw-rw---- 1 user user 3,0K mars  27 08:42 README.md
drwxrwx--x 8 user user 4,0K mars  27 08:42 src
drwxrwx--x 3 user user 4,0K mars  27 08:42 themes
-rw-rw---- 1 user user  95K mars  27 08:42 yarn.lock

~/dev/vuejs.org|master » yarn
yarn install v1.5.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.2: The platform "linux" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 5.74s.

~/dev/vuejs.org|master » yarn start
yarn run v1.5.1
$ hexo server
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: watch /home/user/dev/vuejs.org/themes/vue/ EMFILE
    at _errnoException (util.js:1031:13)
    at FSWatcher.start (fs.js:1397:19)
    at Object.fs.watch (fs.js:1423:11)
    at createFsWatchInstance (/home/user/dev/vuejs.org/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/user/dev/vuejs.org/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/user/dev/vuejs.org/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/user/dev/vuejs.org/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/home/user/dev/vuejs.org/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/home/user/dev/vuejs.org/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:167:5)
error An unexpected error occurred: "Command failed.
Exit code: 2
Command: sh
Arguments: -c hexo server
Directory: /home/user/dev/vuejs.org
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/home/user/dev/vuejs.org/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Seeing that, I tried `node_modules/hexo/bin/hexo generate`, which generated the static content, but then running `yarn start` still output the same error.

The only way currently for launching the hexo server is to use the static flag `node_modules/hexo/bin/hexo server -s`, but that [prevent any watch](https://hexo.io/docs/troubleshooting.html#EMPERM-Error-Windows-Subsystem-for-Linux), so not so good.

**Comment by chrisvfritz** [comment]
I wasn't able to replicate this unfortunately. Could you provide the exact version and distribution of Linux you're using, as well as the Node version?

**Comment by AlexandreBonneau** [comment]
This is on Debian Stretch (fully updated), with node `v9.2.1` and npm `v5.6.0`.

**Comment by chrisvfritz** [comment]
I think it's related to [this problem](https://hexo.io/docs/troubleshooting.html#ENOSPC-Error-Linux), as `EMFILE` basically means too many files open. Increasing the max users watches for the system should fix it.

**Comment by AlexandreBonneau** [comment]
Sorry I forgot to get back to that issue; since then I managed to make it work, but I do not recall what change exactly did the trick.

Right now `ulimit -n` returns `1024` (which is the default), and I'm using node `v9.10.1`.
