### ISSUE TITLE
 unknown block tag: endraw

### ISSUE THREAD

**Issue by airclear** [vuejs/vuejs.org#895]
localhost:vuejs.org airclear$ node -v
v6.10.0
localhost:vuejs.org airclear$ npm -v
3.10.10
localhost:vuejs.org airclear$ hexo -v
hexo: 3.3.5
hexo-cli: 1.0.2
os: Darwin 15.5.0 darwin x64
http_parser: 2.7.0
node: 6.10.0
v8: 5.1.281.93
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2k

```
localhost:vuejs.org airclear$ hexo server -p 4001
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Template render error: (unknown path) [Line 6, Column 2]
  unknown block tag: endraw
    at Object.exports.prettifyError (/Users/airclear/works/projects/vuejs.org/node_modules/nunjucks/src/lib.js:34:15)
    at new_cls.render (/Users/airclear/works/projects/vuejs.org/node_modules/nunjucks/src/environment.js:469:27)
    at new_cls.renderString (/Users/airclear/works/projects/vuejs.org/node_modules/nunjucks/src/environment.js:327:21)
    at /Users/airclear/works/projects/vuejs.org/node_modules/hexo/lib/extend/tag.js:66:9
    at Promise._execute (/Users/airclear/works/projects/vuejs.org/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/Users/airclear/works/projects/vuejs.org/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/airclear/works/projects/vuejs.org/node_modules/bluebird/js/release/promise.js:79:10)
    at Tag.render (/Users/airclear/works/projects/vuejs.org/node_modules/hexo/lib/extend/tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (/Users/airclear/works/projects/vuejs.org/node_modules/hexo/lib/hexo/post.js:253:16)
    at /Users/airclear/works/projects/vuejs.org/node_modules/hexo/lib/hexo/render.js:65:19
    at tryCatcher (/Users/airclear/works/projects/vuejs.org/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/airclear/works/projects/vuejs.org/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/airclear/works/projects/vuejs.org/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/airclear/works/projects/vuejs.org/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/airclear/works/projects/vuejs.org/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/airclear/works/projects/vuejs.org/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/airclear/works/projects/vuejs.org/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/airclear/works/projects/vuejs.org/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
FATAL (unknown path) [Line 6, Column 2]
  unknown block tag: endraw
Template render error: (unknown path) [Line 6, Column 2]
  unknown block tag: endraw
    at Object.exports.prettifyError (/Users/airclear/works/projects/vuejs.org/node_modules/nunjucks/src/lib.js:34:15)
    at new_cls.render (/Users/airclear/works/projects/vuejs.org/node_modules/nunjucks/src/environment.js:469:27)
    at new_cls.renderString (/Users/airclear/works/projects/vuejs.org/node_modules/nunjucks/src/environment.js:327:21)
    at /Users/airclear/works/projects/vuejs.org/node_modules/hexo/lib/extend/tag.js:66:9
    at Promise._execute (/Users/airclear/works/projects/vuejs.org/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/Users/airclear/works/projects/vuejs.org/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/airclear/works/projects/vuejs.org/node_modules/bluebird/js/release/promise.js:79:10)
    at Tag.render (/Users/airclear/works/projects/vuejs.org/node_modules/hexo/lib/extend/tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (/Users/airclear/works/projects/vuejs.org/node_modules/hexo/lib/hexo/post.js:253:16)
    at /Users/airclear/works/projects/vuejs.org/node_modules/hexo/lib/hexo/render.js:65:19
    at tryCatcher (/Users/airclear/works/projects/vuejs.org/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/airclear/works/projects/vuejs.org/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/airclear/works/projects/vuejs.org/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/airclear/works/projects/vuejs.org/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/airclear/works/projects/vuejs.org/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/airclear/works/projects/vuejs.org/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/airclear/works/projects/vuejs.org/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/airclear/works/projects/vuejs.org/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

**Comment by chrisvfritz** [comment]
I'm not able to reproduce this. To ensure it's not a change you made to the code or a problem with module installation, I recommend running:

```
git fetch origin
git reset --hard origin/master
rm -rf node_modules
npm install
```

Then trying again. Hopefully that helps!

**Comment by gbezyuk** [comment]
@chrisvfritz happen to face the same issue at ru.vuejs.org fork now.
```
➜  ru.vuejs.org git:(master) ✗ hexo --version
hexo: 3.3.5
hexo-cli: 1.0.2
os: Darwin 16.4.0 darwin x64
http_parser: 2.7.0
node: 6.9.3
v8: 5.1.281.89
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2j
```

**Comment by gbezyuk** [comment]
Found this while trying to fix the error: https://github.com/hexojs/hexo/issues/1837.

Here is the whole debug output:

```
➜  vuejs.org git:(master) ✗ hexo generate --debug
03:29:03.849 DEBUG Hexo version: 3.3.5
03:29:03.852 DEBUG Working directory: /w/translation-gang/vuejs.org/
03:29:03.955 DEBUG Config loaded: /w/translation-gang/vuejs.org/_config.yml
03:29:03.971 DEBUG Plugin loaded: hexo-deployer-git
03:29:03.972 DEBUG Plugin loaded: hexo-generator-alias
03:29:03.974 DEBUG Plugin loaded: hexo-generator-archive
03:29:03.975 DEBUG Plugin loaded: hexo-generator-category
03:29:03.978 DEBUG Plugin loaded: hexo-generator-feed
03:29:03.978 DEBUG Plugin loaded: hexo-generator-index
03:29:03.979 DEBUG Plugin loaded: hexo-generator-tag
03:29:03.981 DEBUG Plugin loaded: hexo-renderer-ejs
03:29:03.986 DEBUG Plugin loaded: hexo-renderer-marked
03:29:03.987 DEBUG Plugin loaded: hexo-renderer-stylus
03:29:04.062 DEBUG Plugin loaded: hexo-server
03:29:04.064 DEBUG Loading database.
03:29:04.216 INFO  Start processing
03:29:04.277 DEBUG Processed: index.md
03:29:04.278 DEBUG Processed: CNAME
03:29:04.343 DEBUG Processed: _posts/011-component.md
03:29:04.343 DEBUG Processed: _posts/012-release.md
03:29:04.343 DEBUG Processed: _posts/1.0.0-release.md
03:29:04.343 DEBUG Processed: _posts/announcing-2.0.md
03:29:04.343 DEBUG Processed: _posts/common-gotchas.md
03:29:04.343 DEBUG Processed: _posts/march-update.md
03:29:04.343 DEBUG Processed: _posts/vue-011-release.md
03:29:04.343 DEBUG Processed: _posts/vue-cli.md
03:29:04.343 DEBUG Processed: _posts/vue-next.md
03:29:04.344 DEBUG Processed: _posts/vuejs-010-release.md
03:29:04.344 DEBUG Processed: _posts/why-no-template-url.md
03:29:04.344 DEBUG Processed: perf/index.md
03:29:04.344 DEBUG Processed: support-vuejs/index.md
03:29:04.344 DEBUG Processed: images/components.png
03:29:04.345 DEBUG Processed: images/data.png
03:29:04.348 DEBUG Processed: images/fancygrid.png
03:29:04.348 DEBUG Processed: images/hn-architecture.png
03:29:04.349 DEBUG Processed: images/lifecycle.png
03:29:04.349 DEBUG Processed: images/mvvm.png
03:29:04.349 DEBUG Processed: images/hn.png
03:29:04.350 DEBUG Processed: images/props-events.png
03:29:04.350 DEBUG Processed: images/state.png
03:29:04.350 DEBUG Processed: images/transition.png
03:29:04.350 DEBUG Processed: images/typescript-type-error.png
03:29:04.350 DEBUG Processed: images/vue-component.png
03:29:04.350 DEBUG Processed: images/vue-component-with-preprocessors.png
03:29:04.404 DEBUG Theme config loaded.
03:29:04.406 DEBUG Processed: v2/api/index.md
03:29:04.406 DEBUG Processed: v2/cookbook/adding-instance-properties.md
03:29:04.406 DEBUG Processed: v2/cookbook/index.md
03:29:04.406 DEBUG Processed: v2/examples/commits.md
03:29:04.406 DEBUG Processed: v2/examples/deepstream.md
03:29:04.406 DEBUG Processed: v2/examples/elastic-header.md
03:29:04.406 DEBUG Processed: v2/examples/firebase.md
03:29:04.406 DEBUG Processed: v2/examples/grid-component.md
03:29:04.406 DEBUG Processed: v2/examples/hackernews.md
03:29:04.406 DEBUG Processed: v2/examples/index.md
03:29:04.406 DEBUG Processed: v2/examples/modal.md
03:29:04.406 DEBUG Processed: v2/examples/select2.md
03:29:04.407 DEBUG Processed: v2/examples/svg.md
03:29:04.407 DEBUG Processed: v2/examples/todomvc.md
03:29:04.407 DEBUG Processed: v2/examples/tree-view.md
03:29:04.407 DEBUG Processed: v2/guide/class-and-style.md
03:29:04.415 DEBUG Processed: v2/guide/comparison.md
03:29:04.415 DEBUG Processed: v2/guide/components.md
03:29:04.415 DEBUG Processed: v2/guide/computed.md
03:29:04.415 DEBUG Processed: v2/guide/conditional.md
03:29:04.415 DEBUG Processed: v2/guide/custom-directive.md
03:29:04.415 DEBUG Processed: v2/guide/deployment.md
03:29:04.415 DEBUG Processed: v2/guide/events.md
03:29:04.416 DEBUG Processed: v2/guide/forms.md
03:29:04.416 DEBUG Processed: v2/guide/index.md
03:29:04.416 DEBUG Processed: v2/guide/instance.md
03:29:04.416 DEBUG Processed: v2/guide/installation.md
03:29:04.416 DEBUG Processed: v2/guide/join.md
03:29:04.416 DEBUG Processed: v2/guide/list.md
03:29:04.416 DEBUG Processed: v2/guide/migration-vue-router.md
03:29:04.416 DEBUG Processed: v2/guide/migration-vuex.md
03:29:04.416 DEBUG Processed: v2/guide/mixins.md
03:29:04.416 DEBUG Processed: v2/guide/migration.md
03:29:04.416 DEBUG Processed: v2/guide/plugins.md
03:29:04.416 DEBUG Processed: v2/guide/reactivity.md
03:29:04.416 DEBUG Processed: v2/guide/render-function.md
03:29:04.416 DEBUG Processed: v2/guide/routing.md
03:29:04.416 DEBUG Processed: v2/guide/single-file-components.md
03:29:04.416 DEBUG Processed: v2/guide/ssr.md
03:29:04.416 DEBUG Processed: v2/guide/state-management.md
03:29:04.416 DEBUG Processed: v2/guide/syntax.md
03:29:04.417 DEBUG Processed: v2/guide/transitioning-state.md
03:29:04.419 DEBUG Processed: v2/guide/transitions.md
03:29:04.419 DEBUG Processed: v2/guide/typescript.md
03:29:04.419 DEBUG Processed: v2/guide/unit-testing.md
03:29:04.419 DEBUG Processed: _config.yml
03:29:04.420 DEBUG Processed: source/css/benchmark.styl
03:29:04.420 DEBUG Processed: source/css/index.styl
03:29:04.420 DEBUG Processed: source/css/page.styl
03:29:04.421 DEBUG Processed: source/css/search.styl
03:29:04.422 DEBUG Processed: source/images/2mhost.png
03:29:04.422 DEBUG Processed: source/images/actualize.png
03:29:04.422 DEBUG Processed: source/images/chaitin.png
03:29:04.422 DEBUG Processed: source/images/check.png
03:29:04.423 DEBUG Processed: source/images/component_io.png
03:29:04.424 DEBUG Processed: source/images/deepstream.png
03:29:04.424 DEBUG Processed: source/images/down.png
03:29:04.425 DEBUG Processed: source/images/famebroker.png
03:29:04.426 DEBUG Processed: source/images/fancygrid.png
03:29:04.426 DEBUG Processed: source/images/feed.png
03:29:04.426 DEBUG Processed: source/images/htmlburger.png
03:29:04.426 DEBUG Processed: source/images/icons.png
03:29:04.427 DEBUG Processed: source/images/itunescn.png
03:29:04.428 DEBUG Processed: source/images/jsfiddle.png
03:29:04.428 DEBUG Processed: source/images/juejin.png
03:29:04.428 DEBUG Processed: source/images/laravel.png
03:29:04.429 DEBUG Processed: source/images/logo.png
03:29:04.429 DEBUG Processed: source/images/menu.png
03:29:04.429 DEBUG Processed: source/images/monterail.png
03:29:04.429 DEBUG Processed: source/images/patreon.png
03:29:04.429 DEBUG Processed: source/images/paypal.png
03:29:04.430 DEBUG Processed: source/images/search.png
03:29:04.430 DEBUG Processed: source/images/shuttleworth.png
03:29:04.430 DEBUG Processed: source/images/someline.png
03:29:04.430 DEBUG Processed: source/images/stdlib.png
03:29:04.430 DEBUG Processed: source/images/strikingly.png
03:29:04.431 DEBUG Processed: source/images/tde.png
03:29:04.431 DEBUG Processed: source/images/vuejobs.svg
03:29:04.431 DEBUG Processed: source/images/tmvuejs2.png
03:29:04.431 DEBUG Processed: source/images/trisoft.png
03:29:04.431 DEBUG Processed: source/js/common.js
03:29:04.432 DEBUG Processed: source/images/vuejobs.png
03:29:04.432 DEBUG Processed: source/js/css.escape.js
03:29:04.432 DEBUG Processed: source/js/smooth-scroll.min.js
03:29:04.439 DEBUG Processed: source/js/vue.min.js
03:29:04.459 DEBUG Processed: layout/index.ejs
03:29:04.460 DEBUG Processed: layout/layout.ejs
03:29:04.460 DEBUG Processed: layout/page.ejs
03:29:04.460 DEBUG Processed: layout/post.ejs
03:29:04.461 DEBUG Processed: source/js/vue.js
03:29:04.465 DEBUG Processed: layout/partials/ad.ejs
03:29:04.465 DEBUG Processed: layout/partials/ecosystem_dropdown.ejs
03:29:04.465 DEBUG Processed: layout/partials/header.ejs
03:29:04.465 DEBUG Processed: layout/partials/language_dropdown.ejs
03:29:04.465 DEBUG Processed: layout/partials/main_menu.ejs
03:29:04.465 DEBUG Processed: layout/partials/sidebar.ejs
03:29:04.465 DEBUG Processed: layout/partials/sponsors.ejs
03:29:05.283 FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Template render error: (unknown path) [Line 6, Column 2]
  unknown block tag: endraw
    at Object.exports.prettifyError (/w/translation-gang/vuejs.org/node_modules/nunjucks/src/lib.js:34:15)
    at new_cls.render (/w/translation-gang/vuejs.org/node_modules/nunjucks/src/environment.js:469:27)
    at new_cls.renderString (/w/translation-gang/vuejs.org/node_modules/nunjucks/src/environment.js:327:21)
    at /w/translation-gang/vuejs.org/node_modules/hexo/lib/extend/tag.js:66:9
    at Promise._execute (/w/translation-gang/vuejs.org/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/w/translation-gang/vuejs.org/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/w/translation-gang/vuejs.org/node_modules/bluebird/js/release/promise.js:79:10)
    at Tag.render (/w/translation-gang/vuejs.org/node_modules/hexo/lib/extend/tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (/w/translation-gang/vuejs.org/node_modules/hexo/lib/hexo/post.js:253:16)
    at /w/translation-gang/vuejs.org/node_modules/hexo/lib/hexo/render.js:65:19
    at tryCatcher (/w/translation-gang/vuejs.org/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/w/translation-gang/vuejs.org/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/w/translation-gang/vuejs.org/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/w/translation-gang/vuejs.org/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/w/translation-gang/vuejs.org/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/w/translation-gang/vuejs.org/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/w/translation-gang/vuejs.org/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/w/translation-gang/vuejs.org/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
03:29:05.350 DEBUG Database saved
03:29:05.351 FATAL (unknown path) [Line 6, Column 2]
  unknown block tag: endraw
Template render error: (unknown path) [Line 6, Column 2]
  unknown block tag: endraw
    at Object.exports.prettifyError (/w/translation-gang/vuejs.org/node_modules/nunjucks/src/lib.js:34:15)
    at new_cls.render (/w/translation-gang/vuejs.org/node_modules/nunjucks/src/environment.js:469:27)
    at new_cls.renderString (/w/translation-gang/vuejs.org/node_modules/nunjucks/src/environment.js:327:21)
    at /w/translation-gang/vuejs.org/node_modules/hexo/lib/extend/tag.js:66:9
    at Promise._execute (/w/translation-gang/vuejs.org/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/w/translation-gang/vuejs.org/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/w/translation-gang/vuejs.org/node_modules/bluebird/js/release/promise.js:79:10)
    at Tag.render (/w/translation-gang/vuejs.org/node_modules/hexo/lib/extend/tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (/w/translation-gang/vuejs.org/node_modules/hexo/lib/hexo/post.js:253:16)
    at /w/translation-gang/vuejs.org/node_modules/hexo/lib/hexo/render.js:65:19
    at tryCatcher (/w/translation-gang/vuejs.org/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/w/translation-gang/vuejs.org/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/w/translation-gang/vuejs.org/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/w/translation-gang/vuejs.org/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/w/translation-gang/vuejs.org/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/w/translation-gang/vuejs.org/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/w/translation-gang/vuejs.org/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/w/translation-gang/vuejs.org/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
➜  vuejs.org git:(master) ✗ hexo --version
hexo: 3.3.5
hexo-cli: 1.0.2
os: Darwin 16.4.0 darwin x64
http_parser: 2.7.0
node: 6.9.3
v8: 5.1.281.89
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2j
```

**Comment by gbezyuk** [comment]
@Alex-Sokolov what is your experience related to this issue?

**Comment by Alex-Sokolov** [comment]
@gbezyuk re-installing global `hexo-cli` with `--force` flag and no errors
All 172 files generated ok

**Comment by gbezyuk** [comment]
@Alex-Sokolov didn't help. But the issue definitely seems to be related to global hexo configuration.

**Comment by mcrapts** [comment]
Same error, fresh git clone, fresh hexo-cli install.

**Comment by chrisvfritz** [comment]
Very strange. Still unable to reproduce, even with a fresh clone and `hexo-cli` install. I'm using:

```
hexo: 3.3.5
hexo-cli: 1.0.2
os: Darwin 16.5.0 darwin x64
http_parser: 2.7.0
node: 7.0.0
v8: 5.4.500.36
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 51
openssl: 1.0.2j
```

**Comment by mcrapts** [comment]
I'm using Windows, perhaps there's an issue there.

```
hexo: 3.3.5
hexo-cli: 1.0.2
os: Windows_NT 10.0.15063 win32 x64
http_parser: 2.7.0
node: 7.8.0
v8: 5.5.372.43
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 51
openssl: 1.0.2k
icu: 58.2
unicode: 9.0
cldr: 30.0.3
tz: 2016j
```

**Comment by chrisvfritz** [comment]
The problem seems to be OS-independent, but thank you for providing more data to help us triangulate it! I hope we can resolve it soon.

**Comment by Alex-Sokolov** [comment]
Yes, on Windows I have the same problem (earlier tested on OS X).

Little investigation by me:
With stacktrace in debug mode starting from `\hexo\lib\extend\tag.js`
```
  unknown block tag: endraw
Template render error: (unknown path) [Line 6, Column 2]
  unknown block tag: endraw
    at Object.exports.prettifyError (C:\WORKGit\translation-gang\ru.vuejs.org\node_modules\nunjucks\src\lib.js:34:15)
    at new_cls.render (C:\WORKGit\translation-gang\ru.vuejs.org\node_modules\nunjucks\src\environment.js:469:27)
    at new_cls.renderString (C:\WORKGit\translation-gang\ru.vuejs.org\node_modules\nunjucks\src\environment.js:327:21)
    at C:\WORKGit\translation-gang\ru.vuejs.org\node_modules\hexo\lib\extend\tag.js:66:9
```
There is `Tag.prototype.render` function (https://github.com/hexojs/hexo/blob/master/lib/extend/tag.js#L50)
Add `console.log` if there are some errors in `env.renderString` callback
Found that hexo strange auto-replaces where `<pre>` and `<code>` tags placed nearly.
Current replace-regex:
```
str = str.replace(/(?:<pre>)?<code.*>[\s\S]*?<\/code>(?:<\/pre>)?/gm, escapeContent);
```
There are recent changes of this regex made by this pull-request: https://github.com/hexojs/hexo/pull/2461

Before pull string was:
```
str = str.replace(/<pre><code.*>[\s\S]*?<\/code><\/pre>/gm, escapeContent);
```

If locally revert to old version — all generated OK.

**Comment by chrisvfritz** [comment]
@Alex-Sokolov Nice detective work! Strange that it's only happening for _some people_ though. Which version of hexo did you revert to, to fix it?

**Comment by Alex-Sokolov** [comment]
@chrisvfritz Works on 3.2.2, fails on 3.3.5 (latest hexo, after `yarn upgrade`) on OS X too.

**Comment by chrisvfritz** [comment]
I feel like there might still be something we're missing. I've been using 3.3.5 with no issues and it would be strange for a regex issue to only affect some machines. I'm happy to revert to 3.2.2 if it also solves the problem for others though. Can anyone provide confirmation?

**Comment by gbezyuk** [comment]
@chrisvfritz I confirm the issue resolution after rolling back to `hexo 3.2.2`.
@Alex-Sokolov awesome detective work, bro! Just deployed the latest version of the Russian translation.

**Comment by Alex-Sokolov** [comment]
@chrisvfritz maybe you use global installed version? maybe generated files cached and need to run `hexo clean` before?

**Comment by chrisvfritz** [comment]
Locked at 3.2.2. 👍

**Comment by NoahDragon** [comment]
The hexo 3.3.6 fix this issue. https://github.com/hexojs/hexo/pull/2568

**Comment by chrisvfritz** [comment]
Hmm, I finally do get an error with 3.3.6 now:

```
FATAL <pre> tag should be coupled: "undefined" <=> "</pre>"
```

I'll put off upgrading for a while still.
